devtools::load_all()
set.seed(123)
tmpl <- tmpl_stsp_full(1,1,2,sigma_L='chol')
model <- r_model(tmpl, bpoles=1, sd=0.5)
print(model)
cat('\n--- System matrices ---\n')
print(model$sys$A)
print(model$sys$B)
print(model$sys$C)
print(model$sys$D)
cat('\n--- sigma_L ---\n')
print(model$sigma_L)
sigma <- tcrossprod(model$sigma_L)
cat('\n--- sigma ---\n')
print(sigma)
Q <- model$sys$B %*% sigma %*% t(model$sys$B)
R <- model$sys$D %*% sigma %*% t(model$sys$D)
S <- model$sys$B %*% sigma %*% t(model$sys$D)
cat('\n--- Q ---\n')
print(Q)
cat('\n--- R ---\n')
print(R)
cat('\n--- S ---\n')
print(S)
cat('\n--- Eigenvalues of Q and R ---\n')
print(eigen(Q, symmetric=TRUE, only.values=TRUE)$values)
print(eigen(R, symmetric=TRUE, only.values=TRUE)$values)
# Check if positive definite
cat('\n--- Is Q positive definite?', all(eigen(Q, symmetric=TRUE, only.values=TRUE)$values > 1e-10), '\n')
cat('--- Is R positive definite?', all(eigen(R, symmetric=TRUE, only.values=TRUE)$values > 1e-10), '\n')
# Try to compute Cholesky
cat('\n--- Cholesky of Q ---\n')
try(print(chol(Q)))
cat('\n--- Cholesky of R ---\n')
try(print(chol(R)))