# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kf_cpp <- function(A, C, Q, R, S, y_t, P1, a1) {
    .Call(`_RLDM_kf_cpp`, A, C, Q, R, S, y_t, P1, a1)
}

kf2_cpp <- function(A, C, H_t, y_t, P1_R, a1) {
    .Call(`_RLDM_kf2_cpp`, A, C, H_t, y_t, P1_R, a1)
}

ll_kf_cpp <- function(A, C, Q, R, S, y_t, P1, a1, tol) {
    .Call(`_RLDM_ll_kf_cpp`, A, C, Q, R, S, y_t, P1, a1, tol)
}

ll_kf2_cpp <- function(A, C, H_t, y_t, P1_R, a1, tol) {
    .Call(`_RLDM_ll_kf2_cpp`, A, C, H_t, y_t, P1_R, a1, tol)
}

ll_kf_theta_cpp <- function(theta, y, SYS, H_SYS, h_SYS, sigma_L, H_sigma_L, h_sigma_L, VAR, P1, tol, err) {
    .Call(`_RLDM_ll_kf_theta_cpp`, theta, y, SYS, H_SYS, h_SYS, sigma_L, H_sigma_L, h_sigma_L, VAR, P1, tol, err)
}

pf_sir_cpp <- function(A, C, Q, R, S, y_t, P1, a1, N_particles = 1000L, resampling = "systematic", ess_threshold = 0.5) {
    .Call(`_RLDM_pf_sir_cpp`, A, C, Q, R, S, y_t, P1, a1, N_particles, resampling, ess_threshold)
}

pf_apf_cpp <- function(A, C, Q, R, S, y_t, P1, a1, N_particles = 1000L, resampling = "systematic", ess_threshold = 0.5) {
    .Call(`_RLDM_pf_apf_cpp`, A, C, Q, R, S, y_t, P1, a1, N_particles, resampling, ess_threshold)
}

pf_optimal_cpp <- function(A, C, Q, R, S, y_t, P1, a1, N_particles = 1000L, resampling = "systematic", ess_threshold = 0.5) {
    .Call(`_RLDM_pf_optimal_cpp`, A, C, Q, R, S, y_t, P1, a1, N_particles, resampling, ess_threshold)
}

ll_pf_cpp <- function(A, C, Q, R, S, y_t, P1, a1, N_particles = 1000L, filter_type = "sir", resampling = "systematic", ess_threshold = 0.5, N_runs = 10L) {
    .Call(`_RLDM_ll_pf_cpp`, A, C, Q, R, S, y_t, P1, a1, N_particles, filter_type, resampling, ess_threshold, N_runs)
}

showMatrix <- function(X, name) {
    invisible(.Call(`_RLDM_showMatrix`, X, name))
}

rls_exp_cpp <- function(Y, X, r, n_init, allow_neg = TRUE, debug_flag = FALSE) {
    .Call(`_RLDM_rls_exp_cpp`, Y, X, r, n_init, allow_neg, debug_flag)
}

rls_window_cpp <- function(Y, X, ws, allow_neg = TRUE, debug_flag = FALSE) {
    .Call(`_RLDM_rls_window_cpp`, Y, X, ws, allow_neg, debug_flag)
}

outputs_ARMA_cpp <- function(A1, B, t0, u, y) {
    invisible(.Call(`_RLDM_outputs_ARMA_cpp`, A1, B, t0, u, y))
}

outputs_STSP_cpp <- function(A, B, C, D, u, a, y) {
    invisible(.Call(`_RLDM_outputs_STSP_cpp`, A, B, C, D, u, a, y))
}

fbsolve_STSP_cpp <- function(A, B, C, D, u, au, as, y) {
    invisible(.Call(`_RLDM_fbsolve_STSP_cpp`, A, B, C, D, u, au, as, y))
}

solve_rmfd_cpp <- function(poly_inv, poly_fwd, data_in, data_out, t0) {
    invisible(.Call(`_RLDM_solve_rmfd_cpp`, poly_inv, poly_fwd, data_in, data_out, t0))
}

residuals_ARMA_cpp <- function(ib0, B1, A, t0, y, u, dU) {
    invisible(.Call(`_RLDM_residuals_ARMA_cpp`, ib0, B1, A, t0, y, u, dU))
}

residuals_STSP_cpp <- function(A, B, C, D, y, a, u, dPI, dU) {
    invisible(.Call(`_RLDM_residuals_STSP_cpp`, A, B, C, D, y, a, u, dPI, dU))
}

cll_theta_ARMA_cpp <- function(th, y, skip, concentrated, ib0, H_b, h_b, B1, H_B, h_B, a0, A, H_A, h_A, L, H_L, h_L, u, dU) {
    .Call(`_RLDM_cll_theta_ARMA_cpp`, th, y, skip, concentrated, ib0, H_b, h_b, B1, H_B, h_B, a0, A, H_A, h_A, L, H_L, h_L, u, dU)
}

cll_theta_STSP_cpp <- function(th, y, skip, concentrated, pi, H_pi, h_pi, L, H_L, h_L, a, u, dU) {
    .Call(`_RLDM_cll_theta_STSP_cpp`, th, y, skip, concentrated, pi, H_pi, h_pi, L, H_L, h_L, a, u, dU)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_RLDM_RcppExport_registerCCallable`)
})
